name: Terraform Deployment
 
on:
  workflow_dispatch: 
 
jobs:
  terraform:
    name: Despliegue Terraform
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
 
      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6
 
      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREPSSWD }}
 
      - name: Inicializar Terraform
        run: terraform init
        working-directory: ./terraform
 
      - name: Validar Terraform
        run: terraform validate
        working-directory: ./terraform
 
      - name: Plan de Terraform
        run: terraform plan
        working-directory: ./terraform
 
      - name: Apply de Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
